image: node:18-alpine

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: 
    - npm ci
    - npm run test
    - npm run test:e2e

build:
  stage: build
  script:
    - npm ci
    - npm run build
  artifacts:
      paths:
        - dist/*
      expire_in: 3 month
  needs:
    - test

docker-build:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  only:
    - main
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG --destination $CI_REGISTRY_IMAGE:R$CI_PIPELINE_IID
  needs:
    - test
