services:
  so-publisher:
    build:
      context: .
    container_name: so-publisher
    restart: unless-stopped
    environment:
      - PRIVATE_KEY= # Create your own via https://gchq.github.io/CyberChef/#recipe=Generate_ECDSA_Key_Pair('P-256','DER')
      - NETWORK=GENX
    ports:
      - "3000:3000"
      - "5001:5000"
    networks:
      - gaia-x

networks:
  gaia-x:
    external: true

# Pontus-X
