services:
  so-publisher:
    build:
      context: .
    container_name: so-publisher
    restart: unless-stopped
    environment:
      - PRIVATE_KEY= # Create your own via https://gchq.github.io/CyberChef/#recipe=Generate_ECDSA_Key_Pair('P-256','DER')
      - NETWORK=GENX
    ports:
      - "5002:5002"
      - "5001:5001"
    networks:
      - xfsc
      - proxy
    labels:
      traefik.enable: true
      traefik.docker.network: proxy

      # https redirect
      traefik.http.routers.publishingconnector.rule: Host(`publishing-connector.localhost`)
      traefik.http.routers.publishingconnector.entrypoints: web
      traefik.http.routers.publishingconnector.middlewares: https-redirectscheme@file

      traefik.http.routers.publishingconnector-secure.rule: Host(`publishing-connector.localhost`)
      traefik.http.routers.publishingconnector-secure.entrypoints: websecure
      traefik.http.services.publishingconnector-secure.loadbalancer.server.port: 5001
  redis:
    image: 'docker.dragonflydb.io/dragonflydb/dragonfly'
    ulimits:
      memlock: -1
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    hostname: redis-commander
    restart: unless-stopped
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"

networks:
  xfsc:
    external: true
  proxy:
    external: true
