name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:
    branches:
      - '**'

# grant the token permission to publish packages
permissions:
  contents: read
  packages: write

jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    container:
      image: node:18-alpine
    steps:
      - name: Checkout code (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run test
      # - run: npm run test:e2e

  build:
    name: 📦 Build
    runs-on: ubuntu-latest
    needs: test
    container:
      image: node:18-alpine
    steps:
      - name: Checkout code (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run build
      - name: Upload `dist/` artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/**
          retention-days: 90

  docker-build:
    name: 🐋 Docker Build & Push
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')) }}
    steps:
      - name: Checkout code (with submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.ref_name }}
            ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:R${{ github.run_number }}
